[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "jax_lensing_profiles"
authors = [{name = "Coleman Krawczyk", email = "coleman.krawczyk@port.ac.uk"}]
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "herculens @ git+https://github.com/Herculens/herculens"
]

[project.urls]
Home = "https://github.com/Herculens/Jax-Lensing-Profiles"
